spring:
  datasource:
    username: root
    password: xjgj
    url: jdbc:mysql://192.168.1.62:3306/yxy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    druid:
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: 'select 1 from dual'